"""nullable imagepath, typo correction, date_created re-added

Revision ID: 106c8ddbbce9
Revises: f6534fe44b96
Create Date: 2024-04-10 11:31:06.264241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106c8ddbbce9'
down_revision = 'f6534fe44b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('decription')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decription', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
