"""appointments table

Revision ID: 31f5ef64ed28
Revises: a59bd729fcb1
Create Date: 2024-04-28 11:38:05.893416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f5ef64ed28'
down_revision = 'a59bd729fcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('First_Name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('Last_Name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('Email_Address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('Phone_Number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('Appoint_Date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('Appoint_Time', sa.DateTime(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('date_created')
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('Appoint_Time')
        batch_op.drop_column('Appoint_Date')
        batch_op.drop_column('Phone_Number')
        batch_op.drop_column('Email_Address')
        batch_op.drop_column('Last_Name')
        batch_op.drop_column('First_Name')

    # ### end Alembic commands ###
