"""edit to appointment db, datetime

Revision ID: 33c033d2a046
Revises: 31f5ef64ed28
Create Date: 2024-05-03 13:28:01.558596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c033d2a046'
down_revision = '31f5ef64ed28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Appoint_DateTime', sa.DateTime(), nullable=True))
        batch_op.drop_column('Appoint_Time')
        batch_op.drop_column('Appoint_Date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Appoint_Date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('Appoint_Time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('Appoint_DateTime')

    # ### end Alembic commands ###
