"""altered animals model

Revision ID: cf65dbd1e109
Revises: 106c8ddbbce9
Create Date: 2024-04-12 12:36:54.749040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf65dbd1e109'
down_revision = '106c8ddbbce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
